apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: git-push-task
  namespace: default


spec:

  params:

    - name: commit-message
      type: string
      default: "Automatic version update"


  workspaces:

    - name: shared-workspace


  steps:

    - name: commit-push

      image: alpine/git:v2.45.2


      env:

        - name: GIT_USERNAME

          valueFrom:

            secretKeyRef:

              name: github-secret

              key: username


        - name: GIT_TOKEN

          valueFrom:

            secretKeyRef:

              name: github-secret

              key: token



      script: |
        #!/bin/sh
        set -e


        cd $(workspaces.shared-workspace.path)



        echo "================================="
        echo "Configurazione Git"
        echo "================================="


        git config user.email "tekton@example.com"

        git config user.name "Tekton Pipeline"



        echo "================================="
        echo "Stato repository"
        echo "================================="


        git status



        echo "================================="
        echo "Aggiungo modifiche"
        echo "================================="


        git add pom.xml k8s/deployment.yaml



        if git diff --cached --quiet; then

          echo "Nessuna modifica da committare"

          exit 0

        fi



        echo "================================="
        echo "Commit"
        echo "================================="


        git commit -m "$(params.commit-message)"



        echo "================================="
        echo "Push GitHub"
        echo "================================="


        git push \
          https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/filippo-colli/tekton-lab.git \
          HEAD:main



        echo "Push completato"
