apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: spring-maven-build-task
  namespace: default

spec:
  workspaces:
    - name: source

  steps:
    - name: build
      image: maven:3.9.11-eclipse-temurin-21
      workingDir: $(workspaces.source.path)

      env:
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: sonarqube-token
              key: token

      script: |
        #!/bin/sh
        set -e

        chmod +x ./mvnw

        ./mvnw clean verify sonar:sonar \
          -DskipTests \
          -Dsonar.host.url=http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000 \
          -Dsonar.token=$SONAR_TOKEN

        echo "Build e analisi SonarQube completate"

        ls -la target
