apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: spring-buildah-build-task
  namespace: default

spec:

  params:
    - name: IMAGE
      type: string

  workspaces:
    - name: source

  steps:

    - name: build-and-push

      image: quay.io/buildah/stable

      securityContext:
        privileged: true

      workingDir: $(workspaces.source.path)

      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker

      script: |
        #!/bin/sh
        set -eux

        echo "================================="
        echo "Contenuto workspace"
        echo "================================="

        ls -la
        ls -la target || true

        echo "================================="
        echo "Build immagine"
        echo "================================="

        buildah bud \
          --format docker \
          -f Dockerfile \
          -t $(params.IMAGE) .

        echo "================================="
        echo "Login Docker config"
        echo "================================="

        cat /tekton/home/.docker/config.json

        echo "================================="
        echo "Push immagine"
        echo "================================="

        buildah push \
          $(params.IMAGE) \
          docker://$(params.IMAGE)

        echo "================================="
        echo "Buildah completato"
        echo "================================="

      volumeMounts:
        - name: docker-config
          mountPath: /tekton/home/.docker


  volumes:

    - name: docker-config

      secret:
        secretName: dockerhub-secret

        items:
          - key: .dockerconfigjson
            path: config.json
