apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: spring-maven-build-task
  namespace: default

spec:

  workspaces:
    - name: source

  steps:

    - name: build

      image: maven:3.9.11-eclipse-temurin-21

      workingDir: $(workspaces.source.path)

      script: |
        #!/bin/sh
        set -e

        echo "================================="
        echo "Build Maven"
        echo "================================="

        chmod +x ./mvnw

        ./mvnw clean verify -DskipTests

        echo "Build Maven completata"

        ls -la target
