apiVersion: tekton.dev/v1
kind: Pipeline

metadata:
  name: tekton-demo-app-pipeline
  namespace: default

spec:

  params:

    - name: repo-url
      type: string

    - name: image
      type: string
      default: filicolli/tekton-demo-app-test

  workspaces:

    - name: shared-workspace

  tasks:

    - name: clone

      taskRef:
        name: git-clone-task

      params:

        - name: repo-url
          value: $(params.repo-url)

      workspaces:

        - name: output
          workspace: shared-workspace

    - name: prepare-release

      runAfter:
        - clone

      taskRef:
        name: prepare-release-version-task

      workspaces:

        - name: source
          workspace: shared-workspace

    - name: maven-build

      runAfter:
        - prepare-release

      taskRef:
        name: spring-maven-build-task

      workspaces:

        - name: source
          workspace: shared-workspace

    - name: sonarqube-analysis

      runAfter:
        - maven-build

      taskRef:
        name: sonarqube-analysis-task

      workspaces:

        - name: source
          workspace: shared-workspace

    - name: buildah-build

      runAfter:
        - sonarqube-analysis

      taskRef:
        name: spring-buildah-build-task

      params:

        - name: IMAGE
          value: $(params.image):$(tasks.prepare-release.results.version)

      workspaces:

        - name: source
          workspace: shared-workspace

    - name: update-image-version

      runAfter:
        - buildah-build

      taskRef:
        name: update-image-version-task

      params:

        - name: IMAGE
          value: $(params.image)

        - name: VERSION
          value: $(tasks.prepare-release.results.version)

      workspaces:

        - name: source
          workspace: shared-workspace

    - name: prepare-next-snapshot

      runAfter:
        - update-image-version

      taskRef:
        name: prepare-next-snapshot-task

      workspaces:

        - name: source
          workspace: shared-workspace

    - name: git-push

      runAfter:
        - prepare-next-snapshot

      taskRef:
        name: git-push-task

      params:

        - name: commit-message
          value: "Release version and prepare next snapshot"

      workspaces:

        - name: shared-workspace
          workspace: shared-workspace
