apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  name: tekton-demo-app-run-001
  namespace: default

spec:

  pipelineRef:
    name: tekton-demo-app-pipeline

  taskRunTemplate:
    serviceAccountName: spring-deployer

  params:

    - name: repo-url
      value: https://github.com/filippo-colli/tekton-lab.git

    - name: image
      value: filicolli/tekton-demo-app-test


  workspaces:

    - name: shared-workspace

      volumeClaimTemplate:

        spec:

          accessModes:
            - ReadWriteOnce

          resources:

            requests:
              storage: 1Gi
