apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: update-image-version-task
  namespace: default

spec:

  params:

    - name: IMAGE
      type: string

    - name: VERSION
      type: string


  workspaces:

    - name: source


  steps:

    - name: update-image

      image: alpine:3.20

      workingDir: $(workspaces.source.path)

      script: |
        #!/bin/sh
        set -e


        echo "================================="
        echo "Aggiornamento immagine Kubernetes"
        echo "================================="


        FULL_IMAGE="$(params.IMAGE):$(params.VERSION)"


        echo "Nuova immagine:"
        echo "$FULL_IMAGE"


        if [ ! -f k8s/deployment.yaml ]; then

          echo "deployment.yaml non trovato"

          exit 1

        fi


        sed -i "s|image:.*|image: ${FULL_IMAGE}|g" k8s/deployment.yaml


        echo "================================="
        echo "Risultato"
        echo "================================="


        cat k8s/deployment.yaml
