apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-demo-app
  labels:
    app: tekton-demo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: tekton-demo-app

  template:
    metadata:
      labels:
        app: tekton-demo-app

    spec:
      containers:
        - name: tekton-demo-app
          image: filicolli/tekton-demo-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080