apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener

metadata:
  name: tekton-demo-app-listener
  namespace: default

spec:

  serviceAccountName: tekton-triggers-sa

  triggers:

    - triggerRef: tekton-demo-app-trigger
